exp: TextClassification

mode: 
   - train

models: 
    hf_text_classification_model:
          - distilbert-base-uncased

trainfpath: /home/zwang1/cosc426/labs/lab07/news_training_data.txt

validfpath: /home/zwang1/cosc426/labs/lab07/data.txt

modelfpath: /home/zwang1/cosc426/labs/lab07/news_model

loadPretrained: False

numLabels: 3

#samplePercent: 10

epochs: 2

#checkFileColumns: False

#batchSize: 100 


